apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: load-balancer.vma.believe.com
spec:
  compositeTypeRef:
    apiVersion: vma.believe.com/v1alpha1
    kind: xLoadBalancer
  mode: Pipeline
  pipeline:
    - step: environmentConfigs
      functionRef:
        name: function-environment-configs
      input:
        apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          environmentConfigs:
            - type: Reference
              ref:
                name: aws-config
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{$resourceName:= dig "composite" "resource" "metadata" "labels" "crossplane.io/claim-name" "" $.observed}}
            apiVersion: vma.believe.com/v1alpha1
            kind: xIRSA
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: irsa
                crossplane.io/external-name: {{ $resourceName }}
            spec:
              serviceAccountName: {{ .observed.composite.resource.spec.serviceAccountName }}
              resourceConfig:
                {{ .observed.composite.resource.spec.resourceConfig | toYaml | nindent 4 }}
            status:
              roleName: {{ .desired.composite.resource.status.roleName }}
              roleArn: {{ .desired.composite.resource.status.roleArn }}
            ---
            apiVersion: vma.believe.com/v1alpha1
            kind: xIAMPolicy
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: policy
            spec:
              compositionSelector:
                matchLabels:
                  vma.believe.com/provider: aws
                  iampolicies.vma.believe.com/policy-type: write
                  iampolicies.vma.believe.com/service: load-balancer
              roleName: {{ dig "resources" "irsa" "resource" "status" "roleName" "" $.observed }}
              resourceConfig:
                {{ .observed.composite.resource.spec.resourceConfig | toYaml | nindent 4 }}
            ---
            {{ if ne (dig "resources" "irsa" "resource" "status" "roleArn" "" $.observed) "" }}
            apiVersion: helm.crossplane.io/v1beta1
            kind: Release
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: release
                crossplane.io/external-name: {{ $resourceName }}
            spec:
              providerConfigRef:
                name:  helm-provider
              {{ if ne $.observed.composite.resource.spec.resourceConfig.deletionPolicy nil }}
              deletionPolicy: {{ .observed.composite.resource.spec.resourceConfig.deletionPolicy }}
              {{ end }}
              forProvider:
                namespace: {{ dig "composite" "resource" "metadata" "labels" "crossplane.io/claim-namespace" "" $.observed }}
                chart:
                  name: aws-load-balancer-controller
                  repository: https://aws.github.io/eks-charts
                  version: 1.7.2
                values:
                  clusterName: {{ index .context "apiextensions.crossplane.io/environment" "eksClusterName" }}
                  replicaCount: {{ .observed.composite.resource.spec.replicaCount }}
                  serviceAccount:
                    name: {{ dig "resources" "irsa" "resource" "status" "roleName" "" $.observed }}
                    annotations:
                      eks.amazonaws.com/role-arn: {{ dig "resources" "irsa" "resource" "status" "roleArn" "" $.observed }}
                  additionalLabels:
                    tags.datadoghq.com/env: {{ index .context "apiextensions.crossplane.io/environment" "env" }}
                    tags.datadoghq.com/service: aws-load-balancer-controller
            {{ end }}
    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
