apiVersion: artifact.gcp.upbound.io/v1beta1
kind: RegistryRepository
metadata:
  name: content-video
spec:
  forProvider:
    description: Repo for vma images
    format: DOCKER
    location: europe-west1
  providerConfigRef:
    name: gcp