apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xs3irsas.vma.believe.com
spec:
  claimNames:
    kind: S3IRSA
    plural: s3irsas
  group: vma.believe.com
  names:
    kind: xS3IRSA
    plural: xs3irsas
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          description: The Schema for the s3 API
          properties:
            spec:
              type: object
              properties:
                resourceConfig:
                  type: object
                  description: ResourceConfig defines general properties of this resource.
                  properties:
                    bucketName:
                      type: string
                    bucketRegion:
                      type: string
                    expirationDays:
                      type: integer
                    providerRef:
                      type: string
                      description: Which provider will be use to manage this resource
                    deletionPolicy:
                      type: string
                      description: Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                    tags:
                      type: object
                      description: Key-value map of resource tags.
                      additionalProperties:
                        type: string
                  required:
                    - providerRef
                    - bucketName
                    - bucketRegion
              required:
                - resourceConfig