apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xexternalsecrets.vma.believe.com
spec:
  group: vma.believe.com
  claimNames:
    kind: ExternalSecrets
    plural: externalsecrets
  names:
    kind: xExternalSecrets
    plural: xexternalsecrets
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: Defines the desired state of ExternalSecrets
              type: object
              properties:
                resourceConfig:
                  type: object
                  description: ResourceConfig defines general properties of this resource.
                  properties:
                    deletionPolicy:
                      type: string
                      description: Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
            status:
              type: object
              description: Defines the observed state of ExternalSecrets
              properties:
                env:
                  type: string
