apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane-core
  namespace: flux-system
spec:
  releaseName: crossplane-core
  interval: 5m
  chart:
    spec:
      chart: crossplane
      version: '1.15.1'
      sourceRef:
        kind: HelmRepository
        name: crossplane-repository
        namespace: crossplane-system
  values:
    args:
      - --enable-environment-configs
    serviceAccount:
      customAnnotations:
        iam.gke.io/gcp-service-account: crossplane@sbx-test-42-c755.iam.gserviceaccount.com
