apiVersion: confluent.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: sandbox-vma-sa
spec:
  forProvider:
    displayName: sandbox-vma-sa
    description: service account for vma kafka workloads
  providerConfigRef:
    name: confluent-provider