apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xiampolicies.vma.believe.com
spec:
  group: vma.believe.com
  names:
    kind: xIAMPolicy
    plural: xiampolicies
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          description: The Schema for the policies API
          properties:
            spec:
              type: object
              description: PolicySpec defines the desired state of Policy
              properties:
                roleName:
                  type: string
                resourceArn:
                  type: string
                resourceConfig:
                  type: object
                  description: ResourceConfig defines general properties of this resource.
                  properties:
                    name:
                      type: string
                    providerRef:
                      type: string
                      description: Which provider will be use to manage this resource
                    deletionPolicy:
                      type: string
                      description: Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                    tags:
                      type: object
                      description: Key-value map of resource tags.
                      additionalProperties:
                        type: string
                  required:
                    - providerRef
              required:
                - resourceConfig
            status:
              type: object
              description: Defines the observed state of the policy.
              properties:
                policyArn:
                  type: string


