apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: metrics-server
spec:
  forProvider:
    chart:
      name: metrics-server
      repository: https://kubernetes-sigs.github.io/metrics-server
      version: 3.11.0
    namespace: kube-system
    values:
      image:
        repository: public.ecr.aws/eks-distro/kubernetes-sigs/metrics-server
        tag: v0.6.4-eks-1-28-latest
  providerConfigRef:
    name: helm-provider