apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xapplications.vma.believe.com
spec:
  group: vma.believe.com
  claimNames:
    kind: Application
    plural: applications
  names:
    kind: xApplication
    plural: xapplications
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: Defines the desired state of an Application
              type: object
              properties:
                gitRepository:
                  type: object
                  description: Define configuration relatives to the source git repository.
                  properties:
                    secretRef:
                      description: |
                        The secret name containing the Git credentials that is externally created.
                        For HTTPS repositories the secret must contain username and password fields.
                        For SSH repositories the secret must contain identity, identity.pub and known_hosts fields.
                      type: string
                  required:
                    - secretRef
                kustomization:
                  type: object
                  description: Define configuration relatives to the kustomization.
                  properties: &kustomizationProps
                    interval:
                      type: string
                      description: The interval at which to reconcile the Kustomization.
                      default: "5m"
                    retryInterval:
                      type: string
                      description: The interval at which to retry a previously failed reconciliation. When not specified, the controller uses the KustomizationSpec.Interval value to retry failures.
                    path:
                      type: string
                      description: |
                        Path to the directory containing the kustomization.yaml file, or the set of plain YAMLs a kustomization.yaml should be generated for.
                        Defaults to "", which translates to the root path of the SourceRef.
                      default: ""
                    suspend:
                      type: boolean
                      description: Whether the kustomization is suspended
                      default: false
                    force:
                      type: boolean
                      description: If set to true, the controller will replace the resources in-cluster if the patching fails due to immutable field changes.
                      default: false
                    timeout:
                      type: string
                      description: Specify a timeout duration for any operation like building, applying, health checking, etc. performed during the reconciliation process.
                kustomizationList:
                  type: array
                  description: Define configuration relatives to multiples kustomizations.
                  items:
                    type: object
                    properties: *kustomizationProps
                resourceConfig:
                  type: object
                  description: Define configuration relatives to the Application.
                  properties:
                    providerRef:
                      type: string
                      description: Which provider will be use to manage this resource
                    deletionPolicy:
                      type: string
                      description: Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                    tags:
                      type: object
                      description: Key-value map of resource tags.
                      additionalProperties:
                        type: string
              required:
                - gitRepository
                - resourceConfig
