apiVersion: vma.believe.com/v1alpha1
kind: Apisix
metadata:
  name: apisix-test
spec:
  adminKey: XXX
  viewerKey: XXX
  etcdReplicaCount: 1
  ingressControllerVersion: "1.6.1"
  logConfiguration:
    bucketName: test-vma-lb-logs
    bucketRetention: 365
    bucketPrefix: apisix-access-logs
    bucketRegion: eu-west-1
  resourceConfig:
    providerRef: irsa-providerconfig