apiVersion: vma.believe.com/v1alpha1
kind: Apisix
metadata:
  name: apisix-test
spec:
  adminKey: XXX
  viewerKey: XXX
  etcdReplicaCount: 1
  ingressControllerVersion: "1.6.1"
  logConfiguration:
    bucketName: test-vma-lb-logs
    bucketRetention: 365
    bucketPrefix: apisix-access-logs
    bucketRegion: eu-west-1
  customPlugins:
  - pluginName: custom-openid-connect
    configMapName: custom-openid-connect-plugin
    configMapKey: custom-openid-connect.lua
    mountPath: /opts/custom_plugins/apisix/plugins/custom-openid-connect.lua
  - pluginName: custom-datadog-plugin
    configMapName: custom-datadog-plugin
    configMapKey: custom-datadog.lua
    mountPath: /opts/custom_plugins/apisix/plugins/custom-datadog.lua
  resourceConfig:
    providerRef: irsa-providerconfig