apiVersion: vma.believe.com/v1alpha1
kind: ClusterAutoscaler
metadata:
  name: cluster-autoscaler-test
spec:
  serviceAccountName: cluster-autoscaler-test
  autoscalingGroups:
    - name: eks-vma-cronjobs-node-20240321104731042500000008-68c7304f-c312-effa-5820-bbf2744cc7fa
      minSize: 0
      maxSize: 5
  resourceConfig:
    providerRef: irsa-providerconfig