apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: confluent-providerconfig
spec:
  dependsOn:
    - name: crossplane-confluent-provider
  interval: 30s
  path: ../deploy/confluent-providerconfig
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-sync
  timeout: 2m