apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-core
spec:
  interval: 5m
  path: ../deploy/crossplane-core
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-sync
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: crossplane-core
      namespace: crossplane-system
    - kind: Deployment
      name: crossplane
      namespace: crossplane-system
    - kind: Deployment
      name: crossplane-rbac-manager
      namespace: crossplane-system
  timeout: 2m