apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-confluent-provider
spec:
  dependsOn:
    - name: crossplane-core
  interval: 30s
  path: ../deploy/crossplane-confluent-provider
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-sync
  timeout: 2m