apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gcp-providerconfig
spec:
  dependsOn:
    - name: crossplane-gcp-provider
  interval: 30s
  path: ../deploy/gcp-providerconfig
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-sync
  timeout: 2m