apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: helm-providerconfig
spec:
  dependsOn:
    - name: crossplane-helm-provider
  interval: 30s
  path: ../deploy/helm-providerconfig
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-sync
  timeout: 2m