apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: vma-infra
spec:
  dependsOn:
    - name: vma-infra
  interval: 30s
  path: ../deploy/vma-apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-sync
  timeout: 2m