apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: vma-infra
spec:
  dependsOn:
    - name: gcp-providerconfig
    - name: confluent-providerconfig
    - name: kafka-providerconfig
  interval: 30s
  path: ../deploy/vma
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-sync
  timeout: 2m