apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: external-secrets.vma.believe.com
spec:
  compositeTypeRef:
    apiVersion: vma.believe.com/v1alpha1
    kind: xExternalSecrets
  environment:
    environmentConfigs:
      - type: Reference
        ref:
          name: aws-config
  patchSets:
    - name: common-fields-composition
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig
          toFieldPath: spec.resourceConfig
  resources:
    - name: helm-release
      base:
        apiVersion: vma.believe.com/v1alpha1
        kind: xHelmRelease
        spec:
          chartConfig:
            name: external-secrets
            repository: https://charts.external-secrets.io
            version: 0.9.14
      patches:
        - type: PatchSet
          patchSetName: common-fields-composition
        - type: FromEnvironmentFieldPath
          fromFieldPath: env
          toFieldPath: metadata.annotations[crossplane.io/env]
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/env]
          toFieldPath: status.env
        - type: CombineFromComposite
          toFieldPath: spec.values
          combine:
            variables:
              - fromFieldPath: status.env
            strategy: string
            string:
              fmt: |
                commonLabels:
                  tags.datadoghq.com/env: %s
                  tags.datadoghq.com/service: external-secret
