apiVersion: cloudflare.believe.com/v1beta1
kind: ProviderConfig
metadata:
  name: cloudflare-provider
spec:
  credentials:
    source: Secret
    secretRef:
      name: cloudflare-credentials
      namespace: crossplane-system
      key: credentials