apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmetricsserver.vma.believe.com
spec:
  group: vma.believe.com
  claimNames:
    kind: MetricsServer
    plural: metricsserver
  names:
    kind: xMetricsServer
    plural: xmetricsserver
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: Defines the desired state of MetricsServer
              type: object
              properties:
                resourceConfig:
                  type: object
                  description: ResourceConfig defines general properties of this resource.
                  properties:
                    deletionPolicy:
                      type: string
                      description: Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
